# # Pavucontrol floating
# windowrule = float,class:(.*org.pulseaudio.pavucontrol.*)
# windowrule = size 700 600,class:(.*org.pulseaudio.pavucontrol.*)
# windowrule = center,class:(.*org.pulseaudio.pavucontrol.*)
# windowrule = pin,class:(.*org.pulseaudio.pavucontrol.*)
#
# # Blueman Manager
# windowrule = float,class:(blueman-manager)
# windowrule = size 800 600,class:(blueman-manager)
# windowrule = center,class:(blueman-manager)
#
# # Float and center file pickers
# windowrule = float, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
# windowrule = center, class:xdg-desktop-portal-gtk, title:^(Open.*Files?|Save.*Files?|All Files|Save)
#
# # nwg-look
# windowrule = float,class:(nwg-look)
# windowrule = size 700 600,class:(nwg-look)
# windowrule = move 10% 20%,class:(nwg-look)
# windowrule = pin,class:(nwg-look)
